services:
    primary:
        container_name: app
        image: app:latest
        restart: always
        env_file:
            - .env
        ports:
            - ${PORT}:${PORT}
        volumes:
            - .:/app

    postgres:
        container_name: postgres
        image: postgres:latest
        restart: always
        env_file:
            - .env
        ports:
            - ${POSTGRES_PORT}:${POSTGRES_PORT}
        volumes:
            - postgres_data:/var/lib/postgresql/data

    redis:
        container_name: redis
        image: redis:latest
        restart: always
        env_file:
            - .env
        ports:
            - ${REDIS_PORT}:${REDIS_PORT}

volumes:
  postgres_data: