"""Fix password hash

Revision ID: 0002
Revises: 0001
Create Date: 2024-05-24 16:32:10.124617

"""

from typing import Sequence, Union

import sqlalchemy as sa  # noqa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0002"
down_revision: Union[str, None] = "0001"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("user", "password", new_column_name="password_hash")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("user", "password_hash", new_column_name="password")
    # ### end Alembic commands ###
