"""add admin role

Revision ID: 0006
Revises: 0005
Create Date: 2024-06-22 19:21:29.593031

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa  # noqa
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision: str = "0006"
down_revision: Union[str, None] = "0005"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        "public",
        "statusenum",
        ["MEMBER", "ADMIN", "INVITED", "DECLINED", "REQUESTED", "REJECTED"],
        [
            TableReference(
                table_schema="public", table_name="membership", column_name="status"
            )
        ],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        "public",
        "statusenum",
        ["MEMBER", "INVITED", "DECLINED", "REQUESTED", "REJECTED"],
        [
            TableReference(
                table_schema="public", table_name="membership", column_name="status"
            )
        ],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###
