"""add notification model

Revision ID: 0009
Revises: 0008
Create Date: 2024-08-08 12:48:10.093231

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0009"
down_revision: Union[str, None] = "0008"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum("READ", "UNREAD", name="notificationstatusenum").create(op.get_bind())
    op.create_table(
        "notification",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "time", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "status",
            postgresql.ENUM(
                "READ", "UNREAD", name="notificationstatusenum", create_type=False
            ),
            nullable=False,
        ),
        sa.Column("text", sa.String(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("notification")
    sa.Enum("READ", "UNREAD", name="notificationstatusenum").drop(op.get_bind())
    # ### end Alembic commands ###
