name: aws_deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy on AWS
    runs-on: ubuntu-latest

    steps:
      - name: Update and deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_IP }}
          username: ${{ secrets.AWS_USER }}
          key: ${{ secrets.AWS_SSH }}
          script: |
            cd meduzzen_internship
            git pull
            docker stop app || true
            docker rm app || true
            docker compose up --build -d
