name: pytest

on:
  push:
    branches:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest

    - name: Set up Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose
        docker-compose --version

    - name: Create .env file
      run: |
        cp .env.sample .env
        echo "HOST=${{ secrets.HOST }}" >> .env
        echo "PORT=${{ secrets.PORT }}" >> .env
        echo "OAUTH2_SECRET_KEY=${{ secrets.OAUTH2_SECRET_KEY }}" >> .env
        echo "OAUTH2_ALGORITHM=${{ secrets.OAUTH2_ALGORITHM }}" >> .env
        echo "OAUTH2_ACCESS_TOKEN_EXPIRE_DAYS=${{ secrets.OAUTH2_ACCESS_TOKEN_EXPIRE_DAYS }}" >> .env
        echo "AUTH0_DOMAIN=${{ secrets.AUTH0_DOMAIN }}" >> .env
        echo "AUTH0_AUDIENCE=${{ secrets.AUTH0_AUDIENCE }}" >> .env
        echo "AUTH0_ALGORITHMS=${{ secrets.AUTH0_ALGORITHMS }}" >> .env
        echo "POSTGRES_HOST=${{ secrets.POSTGRES_HOST }}" >> .env
        echo "POSTGRES_PORT=${{ secrets.POSTGRES_PORT }}" >> .env
        echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}" >> .env
        echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> .env
        echo "POSTGRES_NAME=${{ secrets.POSTGRES_NAME }}" >> .env
        echo "POSTGRES_TEST_NAME=${{ secrets.POSTGRES_TEST_NAME }}" >> .env
        echo "REDIS_HOST=${{ secrets.REDIS_HOST }}" >> .env
        echo "REDIS_PORT=${{ secrets.REDIS_PORT }}" >> .env
        echo "REDIS_PASSWORD=${{ secrets.REDIS_PASSWORD }}" >> .env

    - name: Start services with Docker Compose
      run: docker-compose up -d
      
    - name: Wait for services to be healthy
      run: |
        for i in {1..10}; do
          docker inspect --format '{{json .State.Health.Status}}' $(docker-compose ps -q postgres) | grep '"healthy"' && break || sleep 5;
          docker inspect --format '{{json .State.Health.Status}}' $(docker-compose ps -q redis) | grep '"healthy"' && break || sleep 5;
        done

    - name: Run tests with pytest
      run: |
        pytest --junitxml=test-results.xml
      env:
        DATABASE_URL: "postgresql://postgres:postgres@localhost:5432/test_db"
        REDIS_URL: "redis://localhost:6379"

    - name: Upload Test Results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: test-results.xml

    - name: Shutdown Docker Compose
      if: always()
      run: docker-compose down
